name: campus_map_app
description: A new Flutter project.
publish_to: 'none' # ✅ pub.dev에 실수로 올리는 것을 방지

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # ✅ Flutter SDK 범위 명시

dependencies:
  flutter:
    sdk: flutter

  # ✅ 상태관리 (화면 간 데이터 전달용)
  provider: ^6.0.1

  # ✅ BLE 비콘 스캔 라이브러리
  flutter_blue_plus: ^1.35.5

  # ✅ iOS 스타일 아이콘 (기본 아이콘 세트)
  cupertino_icons: ^1.0.8

  # ✅ SVG 이미지 로딩 (학교 도면 등)
  flutter_svg: ^2.0.9

  # ✅ 구글 폰트 사용 가능
  google_fonts: ^6.1.0

  # ✅ BLE 비콘 감지용 (보조적으로 사용됨)
  dchs_flutter_beacon: ^0.6.4

  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4           # ✅ Firestore 데이터베이스
  firebase_core: ^3.13.1          # ✅ Firebase 초기화용

  # ✅ 권한 요청 (BLE, 위치, 카메라 등)
  permission_handler: ^11.3.1

  # ✅ UUID 생성기 (비콘 고유 식별 등)
  uuid: ^4.2.2

  # ✅ QR 코드 인식용 카메라 스캐너
  mobile_scanner: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ✅ 코드 정적 검사 및 스타일 검사
  flutter_lints: ^5.0.0

  # ✅ 앱 런처 아이콘 생성용 패키지
  flutter_launcher_icons: ^0.13.1

# ✅ 런처 아이콘 설정 블록 (주의: dev_dependencies 바깥에 위치해야 함)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # ✅ 앱 런처 아이콘 경로

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/campus_map.png
    - assets/images/it_building_1f_map.png
    - assets/images/it_building_2f_map.png
    - assets/images/it_building_3f_map.png
    - assets/images/it_building_4f_map.png
    - assets/images/it_building_5f_map.png
    - assets/images/it_building_6f_map.png
    - assets/images/it_building_7f_map.png
    - assets/images/it_building_8f_map.png
    - assets/images/it_building_9f_map.png
    - assets/images/it_building_10f_map.png
    - assets/images/s.space.png
    - assets/images/i.space.png
    - assets/images/tdm.space.png
    - assets/images/Bookmark.png
    - assets/data/classroom_schedule_final.json  # ✅ 강의실 시간표 데이터
    - assets/data/paths.json
    - assets/data/beacon_test_sample.json                     # ✅ 경로 안내용 샘플 데이터
